### ISSUE TITLE
Can not decompress the clip feature of Activitynet

### ISSUE THREAD

**Issue by Yisen-Feng** [minghangz/cnm#1]
Hi!
I have tried to decompress the Compressed package with haozip and winrar.However,they all told me that the Compressed package has been damaged.Is there something wrong with my decompression?@minghangz
Thank you
![image](https://user-images.githubusercontent.com/70309150/227527635-5288c654-55f9-452f-a68b-bda2a4b2faa0.png)

**Comment by minghangz** [comment]
You don't need to decompress the feature. You should read the hdf5 file with [h5py](https://www.h5py.org/) package.

**Comment by Yisen-Feng** [comment]
> You don't need to decompress the feature. You should read the hdf5 file with [h5py](https://www.h5py.org/) package.

yes，but I need to decompress the Compressed package.
![image](https://user-images.githubusercontent.com/70309150/227555762-9f9fdd7c-fe87-4450-8e30-4afb978423d2.png)

**Comment by minghangz** [comment]
I can decompress them with bandzip.

Maybe you can check the MD5 checksums of these files to ensure they are downloaded correctly. Then you may re-download the incorrect file.

The MD5 checksums are:
```
97622bb8502b747fe3dbbb459fad1af6 *clip_vit_32_features.z01
ae9399d6434ac1f4cdefa13f9579d02e *clip_vit_32_features.z02
ec99c79073be23e14a8b971361832958 *clip_vit_32_features.z03
71e91270929fd7bf0131dfa7971cef97 *clip_vit_32_features.zip
```

**Comment by Yisen-Feng** [comment]
> I can decompress them with bandzip.
> 
> Maybe you can check the MD5 checksums of these files to ensure they are downloaded correctly. Then you may re-download the incorrect file.
> 
> The MD5 checksums are:
> 
> ```
> 97622bb8502b747fe3dbbb459fad1af6 *clip_vit_32_features.z01
> ae9399d6434ac1f4cdefa13f9579d02e *clip_vit_32_features.z02
> ec99c79073be23e14a8b971361832958 *clip_vit_32_features.z03
> 71e91270929fd7bf0131dfa7971cef97 *clip_vit_32_features.zip
> ```

very grateful for your rapid reply,I make it with  re-downloading the incorrect file
